// Regenerates src/schema.ts from the canonical spec schema.
// Run whenever specs/ucp/schema/ucp.schema.json changes.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const candidates = [
  join(here, "../../../specs/ucp/schema/ucp.schema.json"), // workspace layout
  join(here, "../../../schema/ucp.schema.json"), // public monorepo layout
];

const source = candidates.find((p) => {
  try {
    readFileSync(p);
    return true;
  } catch {
    return false;
  }
});
if (!source) {
  console.error("sync-schema: canonical schema not found in", candidates);
  process.exit(1);
}

const schema = JSON.parse(readFileSync(source, "utf8"));
const banner =
  "// GENERATED by tools/sync-schema.mjs from the canonical UCP JSON Schema.\n" +
  "// Do not edit by hand.\n";
writeFileSync(
  join(here, "../src/schema.ts"),
  `${banner}export const ucpSchema = ${JSON.stringify(schema, null, 2)} as const;\n`
);
console.log("sync-schema: src/schema.ts regenerated from", source);
